# Generated by Django 6.0.2 on 2026-02-10 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineContent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(max_length=50)),
                ('related_entity_id', models.UUIDField()),
                ('local_file_path', models.CharField(max_length=255)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_contents', to='accounts.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'content_type'], name='offline_off_student_4ec7e4_idx')],
            },
        ),
    ]
