# Generated by Django 6.0.2 on 2026-02-10 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorAnalysis',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_explanation', models.TextField()),
                ('helpful_hint', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user_answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='error_analysis', to='exercises.useranswer')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
